# Generated by Django 5.1.6 on 2025-06-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_scolara', '0006_utilizator_data_suspendare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recenzie',
            name='respins',
            field=models.BooleanField(default=False),
        ),
    ]
