# Generated by Django 5.1.6 on 2025-02-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_scolara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elev',
            name='nr_matricol',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='cod_unic',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
