# Generated by Django 5.1.6 on 2025-02-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_scolara', '0002_alter_elev_nr_matricol_alter_exemplar_cod_unic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliotecar',
            name='id',
        ),
        migrations.AddField(
            model_name='bibliotecar',
            name='id_bibliotecar',
            field=models.CharField(default='01.01.2000', max_length=20, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bibliotecar',
            name='data_nasterii',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='elev',
            name='data_nasterii',
            field=models.DateField(),
        ),
    ]
