# Generated by Django 5.1.6 on 2025-02-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_scolara', '0003_remove_bibliotecar_id_bibliotecar_id_bibliotecar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliotecar',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='elev',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
