# Generated by Django 5.1.6 on 2025-02-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_scolara', '0004_bibliotecar_username_elev_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliotecar',
            name='username',
        ),
        migrations.RemoveField(
            model_name='elev',
            name='username',
        ),
    ]
