# Generated by Django 5.1.6 on 2025-03-28 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_scolara', '0003_utilizator_domenii_interes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='publicatie',
        ),
        migrations.AddField(
            model_name='carte',
            name='editura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exemplar',
            name='an_publicatie',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AddField(
            model_name='exemplar',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
