# Generated by Django 5.1.6 on 2025-05-24 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_scolara', '0004_remove_carte_isbn_remove_carte_publicatie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplar',
            name='an_publicatie',
        ),
        migrations.RemoveField(
            model_name='exemplar',
            name='isbn',
        ),
        migrations.AddField(
            model_name='carte',
            name='an_publicatie',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AddField(
            model_name='carte',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
