# Generated by Django 5.1.6 on 2025-06-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_scolara', '0005_remove_exemplar_an_publicatie_remove_exemplar_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizator',
            name='data_suspendare',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilizator',
            name='zile_suspendare',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
