# Generated by Django 5.1.6 on 2025-03-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_scolara', '0002_tokenresetareparola'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizator',
            name='domenii_interes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
