# Generated by Django 5.1.6 on 2025-02-18 11:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotecar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('prenume', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('parola', models.CharField(max_length=255)),
                ('nr_telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('adresa', models.TextField(blank=True, null=True)),
                ('oras', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('data_inregistrare', models.DateTimeField(auto_now_add=True)),
                ('poza', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bibliotecar',
                'verbose_name_plural': 'Bibliotecari',
                'db_table': 'bibliotecari',
                'ordering': ['nume', 'prenume'],
            },
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('publicatie', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1400), django.core.validators.MaxValueValidator(2025)])),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('exemplare_disponibile', models.PositiveIntegerField(default=1)),
                ('categorie', models.CharField(choices=[('Literatură', 'Literatură'), ('Științe exacte', 'Științe exacte'), ('Științe sociale', 'Științe sociale'), ('Educație', 'Educație'), ('Dezvoltare personală', 'Dezvoltare personală')], max_length=30)),
                ('poza', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Carte',
                'verbose_name_plural': 'Cărți',
                'db_table': 'carti',
                'ordering': ['titlu'],
            },
        ),
        migrations.CreateModel(
            name='Elev',
            fields=[
                ('nr_matricol', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Numărul matricol trebuie să fie de forma AB123 (2 litere + 3 cifre).', regex='^[A-Z]{2}\\d{3}$')])),
                ('nume', models.CharField(max_length=255)),
                ('prenume', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('parola', models.CharField(max_length=255)),
                ('clasa', models.CharField(max_length=10)),
                ('nr_telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('adresa', models.TextField(blank=True, null=True)),
                ('oras', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('data_inregistrare', models.DateTimeField(auto_now_add=True)),
                ('poza', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Elev',
                'verbose_name_plural': 'Elevi',
                'db_table': 'elevi',
                'ordering': ['nume', 'prenume'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilizator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('actiune', models.TextField(blank=True, null=True)),
                ('data_actiune', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log activitate',
                'verbose_name_plural': 'Loguri activitate',
                'db_table': 'loguri',
                'ordering': ['-data_actiune'],
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_unic', models.CharField(help_text='Cod unic al exemplarului, de ex. C12345', max_length=20, unique=True)),
                ('locatie', models.CharField(blank=True, max_length=255, null=True)),
                ('stare', models.CharField(choices=[('disponibil', 'Disponibil'), ('imprumutat', 'Împrumutat'), ('deteriorat', 'Deteriorat')], default='disponibil', max_length=20)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplare', to='biblioteca_scolara.carte')),
            ],
            options={
                'verbose_name': 'Exemplar',
                'verbose_name_plural': 'Exemplare',
                'db_table': 'exemplare',
                'ordering': ['carte', 'cod_unic'],
            },
        ),
        migrations.CreateModel(
            name='Imprumut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_imprumut', models.DateField(auto_now_add=True)),
                ('data_scadenta', models.DateField(blank=True, null=True)),
                ('data_restituire', models.DateField(blank=True, null=True)),
                ('returnat', models.BooleanField(default=False)),
                ('elev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imprumuturi', to='biblioteca_scolara.elev')),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imprumuturi', to='biblioteca_scolara.exemplar')),
            ],
            options={
                'verbose_name': 'Împrumut',
                'verbose_name_plural': 'Împrumuturi',
                'db_table': 'imprumuturi',
                'ordering': ['-data_imprumut'],
            },
        ),
        migrations.CreateModel(
            name='Recenzie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('comentariu', models.TextField(blank=True, null=True)),
                ('data_postare', models.DateTimeField(auto_now_add=True)),
                ('aprobat', models.BooleanField(default=False)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzii', to='biblioteca_scolara.carte')),
                ('elev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzii', to='biblioteca_scolara.elev')),
            ],
            options={
                'verbose_name': 'Recenzie',
                'verbose_name_plural': 'Recenzii',
                'db_table': 'recenzii',
                'ordering': ['-data_postare'],
            },
        ),
    ]
